# Generated by Django 5.0.6 on 2024-06-22 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='money',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='money'),
        ),
    ]
